import { uiError } from './ui-error';
import { useState } from 'react';
import type { AgentConfig, EffectiveModel, ModelProvider } from './types';

export function AgentPolicyPanel({ initial, models, providers, sandbox, disabled, onSaved }: { onSaved: (models: EffectiveModel[]) => void; initial: AgentConfig; models: EffectiveModel[]; providers: ModelProvider[]; sandbox: { available: boolean; backend: string | null; reason: string }; disabled: boolean }) {
  const [draft, setDraft] = useState(initial);
  const [origins, setOrigins] = useState(initial.allowedOrigins.join('\n'));
  const [apis, setApis] = useState(JSON.stringify(initial.apiEndpoints, null, 2));
  const [prices, setPrices] = useState(JSON.stringify(initial.prices, null, 2));
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [error, setError] = useState('');
  const number = (key: 'maxWorkers' | 'maxCalls' | 'maxTokens' | 'modelTimeoutSeconds' | 'contextWindow' | 'maxOutputTokens', label: string, min: number, max: number) => <label>{label}<input type="number" min={min} max={max} value={draft[key]} onChange={(event) => setDraft({ ...draft, [key]: Number(event.target.value) })} /></label>;
  const save = async () => {
    setBusy(true); setNotice(''); setError('');
    try {
      const saved = await window.zhuge.saveAgentConfig({ ...draft, allowedOrigins: origins.split('\n').map((item) => item.trim()).filter(Boolean), apiEndpoints: JSON.parse(apis), prices: JSON.parse(prices) });
      setDraft(saved); onSaved((await window.zhuge.runtimeSettings()).models); setNotice('已保存，新任务使用这些设置。暂停任务沿用原来的预算和权限。');
    } catch (error) { setError(uiError(error)); } finally { setBusy(false); }
  };
  return <section><h3>分工与用量</h3><p className="settings-hint">“分工完成”会先生成步骤，由你确认后执行。子任务默认使用当前服务商的低成本模型，可以单独选择；需求检查保持独立。最终核对使用执行模型，并能读取实际产物。最多同时运行 2 个任务，全局最多 8 个工作节点，等待队列有上限。</p>
    <fieldset disabled={disabled || busy}>
      <div className="runtime-form-grid"><label>子代理服务商<select aria-label="子代理服务商" value={draft.workerProvider} onChange={(event) => setDraft({ ...draft, workerProvider: event.target.value as AgentConfig['workerProvider'], workerModel: '', workerBaseUrl: '' })}><option value="same">跟随执行模型的服务商</option>{providers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>子代理模型<input aria-label="子代理模型" list="worker-model-options" value={draft.workerModel} placeholder="自动选择该服务商的低成本模型" onChange={(event) => setDraft({ ...draft, workerModel: event.target.value })} /><datalist id="worker-model-options">{providers.find((item) => item.id === (draft.workerProvider === 'same' ? models[0]?.provider : draft.workerProvider))?.models.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</datalist></label></div>
      <label>子代理 API 地址（可留空）<input aria-label="子代理 API 地址" value={draft.workerBaseUrl} onChange={(event) => setDraft({ ...draft, workerBaseUrl: event.target.value })} placeholder="使用该服务商已保存的地址" /></label>
      <label>检查失败后最多调整计划几次<input type="number" min="0" max="5" value={draft.maxPlanRevisions} onChange={(event) => setDraft({ ...draft, maxPlanRevisions: Number(event.target.value) })} /></label>
      <details><summary>模型能力与实际限制</summary><p className="settings-hint">官方地址与模型名完全匹配时使用 SDK 目录。自定义地址和未知模型使用保守限制；这里可按服务商说明手动调整。任务预算会进一步限制窗口和输出。图片能力仅记录模型信息，当前应用只发送文本和文档内容。</p>{models.map((model) => { const key = model.key, manual = draft.modelCapabilities[key]; return <section key={model.role}><h4>{{ executor: '执行', worker: '子代理', planner: '需求检查与规划' }[model.role]} · {model.model || '未选择'}</h4><p className="settings-hint">{model.source === 'sdk-catalog' ? '来自模型目录' : model.source === 'manual' ? '手动指定' : '能力未确认，使用保守限制'} · 窗口 {model.contextWindow?.toLocaleString()} · 输出 {model.maxTokens?.toLocaleString()}</p>{manual ? <><div className="runtime-form-grid"><label>模型上下文窗口<input type="number" min="4096" value={manual.contextWindow ?? model.contextWindow} onChange={(event) => setDraft({ ...draft, modelCapabilities: { ...draft.modelCapabilities, [key]: { ...manual, contextWindow: Number(event.target.value) } } })} /></label><label>模型最大输出<input type="number" min="256" value={manual.maxTokens ?? model.maxTokens} onChange={(event) => setDraft({ ...draft, modelCapabilities: { ...draft.modelCapabilities, [key]: { ...manual, maxTokens: Number(event.target.value) } } })} /></label></div>{(['tools', 'reasoning', 'vision'] as const).map((field) => <label className="management-check" key={field}><input type="checkbox" checked={manual[field] ?? model[field]} onChange={(event) => setDraft({ ...draft, modelCapabilities: { ...draft.modelCapabilities, [key]: { ...manual, [field]: event.target.checked } } })} />{{ tools: '工具调用', reasoning: '推理', vision: '模型支持图片' }[field]}</label>)}<button type="button" className="settings-manage" onClick={() => { const next = { ...draft.modelCapabilities }; delete next[key]; setDraft({ ...draft, modelCapabilities: next }); }}>恢复自动识别</button></> : <button type="button" className="settings-manage" onClick={() => setDraft({ ...draft, modelCapabilities: { ...draft.modelCapabilities, [key]: { contextWindow: model.contextWindow, maxTokens: Math.min(model.maxTokens || 4096, Math.floor((model.contextWindow || 32768) / 2)), reasoning: model.reasoning, vision: model.vision, tools: model.tools } } })}>手动指定能力</button>}</section>; })}</details>
      <div className="runtime-form-grid">{number('maxWorkers', '每个任务同时工作的节点', 1, 8)}{number('maxCalls', '整个任务的模型调用上限', 1, 500)}</div>
      <div className="runtime-form-grid">{number('maxTokens', '整个任务的 Token 上限', 1000, 10000000)}<label>费用上限（USD，可留空）<input type="number" min="0.001" step="0.01" value={draft.maxCost ?? ''} onChange={(event) => setDraft({ ...draft, maxCost: event.target.value === '' ? null : Number(event.target.value) })} /></label></div>
      {number('modelTimeoutSeconds', '每次模型请求的时间上限（秒）', 30, 900)}
      <p className="settings-hint">发起请求前预留输入和输出预算。供应商没有返回用量时标为估算；价格未登记时显示费用未知。设置费用上限后，未登记价格的模型不会启动。</p>
      <details><summary>上下文与模型单价</summary><div className="runtime-form-grid">{number('contextWindow', '上下文窗口上限', 8000, 1000000)}{number('maxOutputTokens', '单次输出上限', 256, 32000)}</div><label>每百万 Token 的 USD 单价（JSON）<textarea rows={5} aria-label="模型价格" value={prices} onChange={(event) => setPrices(event.target.value)} /></label><p className="settings-hint">以 provider:model 为键，填写 input、output、cacheRead、cacheWrite 四个非负单价。按你的服务商报价填写；不会把未登记价格算成免费。</p></details>
      <h3>命令隔离</h3><p className="settings-hint">{sandbox.available ? `可用：${sandbox.backend}` : sandbox.reason}。沙箱只允许读取工作目录和系统运行文件，写入工作目录；项目配置与规则文件禁止修改。macOS 以外没有此执行后端。</p>
      <label className="management-check"><input type="checkbox" checked={draft.sandbox} onChange={(event) => setDraft({ ...draft, sandbox: event.target.checked })} />在系统沙箱中运行命令和本地 MCP</label>
      <label className="management-check"><input type="checkbox" checked={draft.network} onChange={(event) => setDraft({ ...draft, network: event.target.checked })} />允许沙箱进程联网（仍需开启“联网工具”）</label>
      <details><summary>浏览器与 API 连接</summary><p className="settings-hint">浏览器使用独立临时会话。登记可访问来源后，每次读取、点击或填值仍会确认。API 仅访问你登记的地址与方法。这里不填写密钥。</p><label>浏览器来源（每行一个 HTTPS origin）<textarea rows={3} value={origins} onChange={(event) => setOrigins(event.target.value)} placeholder="https://example.com" /></label><label>API 地址（JSON 数组）<textarea rows={5} value={apis} onChange={(event) => setApis(event.target.value)} placeholder={'[{"name":"catalog","url":"https://example.com/api","methods":["GET"]}]'} /></label></details>
      <button className="settings-manage" onClick={save}>{busy ? '保存中…' : '保存分工、预算与工具设置'}</button>
    </fieldset>{notice && <p role="status">{notice}</p>}{error && <p className="settings-error" role="alert">{error}</p>}
  </section>;
}
